vversion: '3.4'

services:
  one-api:
    image: justsong/one-api-en
    container_name: one-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "3001:3000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - SQL_DSN=root:123456@tcp(host.docker.internal:3306)/one-api  # Змініть цей рядок або закоментуйте, щоб використовувати SQLite як базу даних
      - REDIS_CONN_STRING=redis://redis
      - SESSION_SECRET=pWh4xA0aMq  # Змініть на випадковий рядок
      - TZ=Asia/Shanghai
#      - NODE_TYPE=slave  # Для розгортання на кількох машинах, розкоментуйте цей рядок для підкоресленої ноди
#      - SYNC_FREQUENCY=60  # Для регулярного завантаження даних з бази даних, розкоментуйте цей рядок
#      - FRONTEND_BASE_URL=https://openai.justsong.cn  # Для розгортання на кількох машинах, розкоментуйте цей рядок для підкоресленої ноди

    depends_on:
      - redis
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk '{print $2}' | grep 'true'" ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:latest
    container_name: redis
    restart: always
